### PR TITLE
Don't escape already escaped chars

### PR DESCRIPTION
**Pull request by gordonsh24**
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-5981

@OnTheGoSystems/wpml @OnTheGoSystems/compatibility

### CODE REVIEW

**Comment by dgwatkins** [comment]
@gordonsh24 I feel we are just patching the problem this way. The origin of the problem must be further up.

I am not 100% sure about it so I really prefer @strategio to take a look in this case.

**Comment by gordonsh24** [comment]
@dgwatkins the problem is that the attribute already contains escaped text like: `My text A &amp;  B and other`. When you transform it with `htmlspecialchars` `&` character will be escaped and we will get `My text A &amp;amp;  B and other`.

I don't see other ways of fixing this issue.

**Comment by dgwatkins** [comment]
Does `My text A &amp; B ` come like this directly from the post_content?

If so, you have my approval.

**Comment by gordonsh24** [comment]
@dgwatkins yes, it does. It is a text provided by the user as DIVI button caption.

**Comment by dgwatkins** [comment]
:+1: @gordonsh24

**Review by dgwatkins — APPROVED** [review]

**Review by strategio — APPROVED** [review]
+1 @gordonsh24

**Pull request merged**
